### PR TITLE
Add kernels for GELU, Swish, and clipped_linear

### PR DESCRIPTION
**Pull request by danieldk**
CUDA kernels for some of the newly-added activation functions.

### CODE REVIEW

**Comment by danieldk** [comment]
@explosion-bot please test_gpu

**Review by svlandeg — COMMENTED** [review]
Discussed that this one was fine to merge, but do you know what the failing test is about; @danieldk ?

**Comment by danieldk** [comment]
> Discussed that this one was fine to merge, but do you know what the failing test is about; @danieldk ?

Looks similar to https://github.com/explosion/thinc/pull/580.

**Comment by danieldk** [comment]
@explosion-bot please test_gpu

**Pull request merged**
