### PR TITLE
Fixes for slow tests

### PR DESCRIPTION
**Pull request by shadeMe**
Will leave this in draft mode until `explosionbot` is updated to support the Buildkite thinc slow test suite. 

### Requirements
* explosion/explosion-bot#3
* #672

### CODE REVIEW

**Comment by shadeMe** [comment]
@explosion-bot please test_slow

**Comment by shadeMe** [comment]
@explosion-bot please test_slow

**Comment by shadeMe** [comment]
@explosion-bot please test_slow

**Comment by shadeMe** [comment]
@explosion-bot please test_gpu

**Comment by shadeMe** [comment]
Now passes both slow and GPU tests.

**Comment by svlandeg** [comment]
What about when running the slow tests on GPU? (I think we want to add this command to both `spacy` and `think`)

**Comment by shadeMe** [comment]
@svlandeg I'll open a new, separate PR for `test_slow_gpu`.

**Review by svlandeg — APPROVED** [review]
This PR looks good - go ahead and merge it in if you're done with it!

**Pull request merged**
