### PR TITLE
Do not use an explicit loop in unflatten

### PR DESCRIPTION
**Pull request by danieldk**
...to avoid many small GPU <-> CPU transfers.

I still have to benchmark this change to see if this leads to a meaningful training time difference.

### CODE REVIEW

**Comment by danieldk** [comment]
@explosion-bot please test_gpu

**Review by honnibal — APPROVED** [review]

**Comment by svlandeg** [comment]
@danieldk : looks good! Feel free to merge in once you're done with your benchmarks and everything looks good :-)

**Comment by danieldk** [comment]
Just a status update: I want to benchmark this a little more.

**Comment by danieldk** [comment]
I did more benchmarks and this change seems to make training slightly slower (2-3%) and inference slightly faster by the same amount. Since a declarative style is nicer in general and since this should scale better (the looping over the array will get more expensive with longer lengths arrays), I'll merge this.

**Pull request merged**
