### PR TITLE
Update for pydantic 1.7 and python 3.9

### PR DESCRIPTION
**Pull request by adrianeboyd**
* Rename `Ragged._cumsums` to `Ragged.cumsums` so it's not flagged as an invalid field.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
There is maybe some way to get this to work as a private attribute or having it ignore fields that start with underscore, but I couldn't get it to work.

**Comment by adrianeboyd** [comment]
Maybe this should be 1.7.1 instead because of the dataclasses arbitrary types thing?

**Comment by honnibal** [comment]
What's the deal with this invalid field thing? You can't have private fields on a dataclass?

It's a bit annoying, because I don't want that to be part of the public interface =/

**Comment by adrianeboyd** [comment]
I know, but if this is the only thing holding up python 3.9 support maybe we could at temporarily modify it. But maybe someone more knowledgeable (@tiangolo?) knows how to configure this correctly?

You get this warning from the `is_valid_field` check:

```
RuntimeWarning: fields may not start with an underscore, ignoring "_cumsums"
```

and then the:

```
X -> _cumsums   extra fields not permitted
```

I things like tried adding `underscore_attrs_are_private` to `_ArgModelConfig` and it didn't seem to do what I expected, but I don't understand all the details here.

**Comment by tiangolo** [comment]
I'm sorry for the delay, my GitHub notifications are a mess, I have 1500 unread emails. :see_no_evil:

**Pull request merged**
