### PR TITLE
testing pydantic v1.10.0a1

### PR DESCRIPTION
**Pull request by samuelcolvin**
see https://github.com/explosion/spaCy/pull/11371

### TO NOT MERGE

This is pull request is just to test pydantic v1.10, see https://github.com/pydantic/pydantic/discussions/4359

### CODE REVIEW

**Comment by adrianeboyd** [comment]
You'll also want to update `setup.cfg`.

**Comment by samuelcolvin** [comment]
thanks, this has already caught https://github.com/pydantic/pydantic/pull/4424. 

I'll make a new patch release, then update the PR.

**Comment by samuelcolvin** [comment]
Just a quick warning, something, I think [this line](https://github.com/explosion/thinc/blob/01eb6b7808af308983bfd71fd456710e50f6e08d/azure-pipelines.yml#L85) is installing an old version of typing-extensions and upsetting quite a few packages.

From the test log:

```
pydantic 1.10.0a2 requires typing-extensions>=4.1.0, but you have typing-extensions 3.7.4.3 which is incompatible.
mypy 0.961 requires typing-extensions>=3.10, but you have typing-extensions 3.7.4.3 which is incompatible.
black 22.6.0 requires typing-extensions>=3.10.0.0; python_version < "3.10", but you have typing-extensions 3.7.4.3 which is incompatible.
```

**Comment by samuelcolvin** [comment]
Pydantic v1.10 drops support for python 3.6.

**Comment by adrianeboyd** [comment]
We have not made any official decisions about dropping python 3.6 compatibility. There aren't many advantages for our current codebase in dropping python 3.6, I think there will be more for dropping python 3.7.

**Comment by samuelcolvin** [comment]
That's fine, just letting you know.

Removing 3.6 allowed some significant improvements in pydantic's code base.

**Comment by samuelcolvin** [comment]
Great, this is passing except for 3.6 which is expected.

**Pull request closed without merging**
