### PR TITLE
Revert uninit'd allocs in `Numpy.reduce_max` introduced in #632. 

### PR DESCRIPTION
**Pull request by shadeMe**
This change broke `spancat` tests in the spaCy test suite.

### CODE REVIEW

**Review by danieldk — APPROVED** [review]

**Comment by danieldk** [comment]
Why are there so many commits for a one-liner? Seems like some merges?

**Comment by shadeMe** [comment]
Yeah, I was wondering that myself. I was expecting 3 - one for each merge and one for the change itself - but GitHub doesn't seem to have identified that the rest are already part of the commit history in the target branch 🤷

**Comment by svlandeg** [comment]
Perhaps because the original PR was squashed? Would it make sense to just redo this PR from a clean copy & add the one commit?

**Comment by svlandeg** [comment]
I don't care strongly, but it does look a bit weird 🤷

**Comment by shadeMe** [comment]
Yeah, I can do that.

**Comment by shadeMe** [comment]
New PR - https://github.com/explosion/thinc/pull/636

**Pull request closed without merging**
